services:
  db:
    image: postgres:15-alpine
    container_name: rbac_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rbac_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresqlrbac_db/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: rbac_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=rbac_db
      - JWT_SECRET=supersecret123
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rbac_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
